domain: craigsmitham.github.io
url: "https://craigsmitham.github.io"
# baseurl: ""
title: "Craig Smitham"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - serve.cmd